all:
  children:
    webservers:
      hosts:
        10.128.0.6:
          deps:
            - gcc
            - glibc
            - glibc-common
            - wget
            - unzip
            - httpd
            - php
            - gd
            - gd-devel
            - perl
            - postfix
            - glibc-common
            - gettext
            - automake
            - autoconf
            - openssl-devel
            - net-snmp
            - net-snmp-utils
          web: 
            - httpd
            - nagios
        10.128.0.7:
          deps:
            - autoconf
            - gcc
            - libc6
            - make
            - wget
            - unzip
            - apache2
            - php
            - libapache2-mod-php7.2
            - libgd-dev
            - bc
            - gawk
            - dc
            - build-essential
            - snmp
            - libnet-snmp-perl
            - gettext
          web: 
            - apache2
            - nagios
